export const company = {name:'SIRAL Corporation',email:'info@siralstrategy.com',support:'support@siralstrategy.com',address:['111 Buck Rd, Suite 200 Unit 2','Huntingdon Valley, PA 19006'],socials:[['LinkedIn','https://www.linkedin.com/company/siral-corporation/'],['Instagram','https://www.instagram.com/siral__corporation?igsh=ZW9iam9vc2J0aHF3&utm_source=qr'],['Facebook','https://www.facebook.com/share/1AzwCzrRbo/?mibextid=wwXIfr']]};
export const services = [
 {slug:'business-consulting',name:'Business Consulting',group:'Strategy',icon:'Compass',tag:'A clearer direction',headline:['Make your next move','a considered one.'],short:'Turn a business challenge into a focused, practical plan.',intro:'When priorities compete, a clear outside perspective helps. Bring your goals, operational challenges and questions into one conversation, then decide what deserves your attention first.',needs:['You have opportunities, but need clearer priorities.','Your operations have become harder to manage.','You are planning a change or a new stage of growth.'],deliverables:[['Business review','A shared view of your goals, current structure and obstacles.'],['Priority roadmap','A practical sequence of actions linked to your business objectives.'],['Decision framework','Clear criteria to help you choose where to invest time and resources.']],questions:[['Where does consulting start?','With your business: what you want to achieve, what is working and what keeps getting in the way. The scope is agreed after that conversation.'],['Can this lead to implementation?','We can discuss related marketing, branding or ongoing support needs as part of a connected engagement.']],related:['marketing-strategy','growth-optimization']},
 {slug:'marketing-strategy',name:'Marketing Strategy',group:'Strategy',icon:'Target',tag:'Focus before activity',headline:['Reach the right people.','With the right message.'],short:'Align your positioning, audience and channels around a clear goal.',intro:'A useful marketing strategy connects the people you want to reach with the reason they should choose you. Define that connection before deciding what to publish, promote or invest in.',needs:['Your marketing feels busy, but lacks a clear direction.','You need to reach a more specific audience.','Your message is different across channels.'],deliverables:[['Audience & positioning','A clearer definition of who you serve and the value you bring.'],['Channel priorities','A focused approach to the channels relevant to your audience.'],['Action & measurement plan','Agreed activities and a framework for reviewing progress.']],questions:[['Is this the same as digital marketing?','Strategy defines the direction: audience, message and priorities. Digital marketing puts the relevant parts of that direction into action online.'],['Do we need to use every channel?','No. The plan should focus on channels that fit your audience, goals and available resources.']],related:['digital-marketing','brand-development']},
 {slug:'digital-marketing',name:'Digital Marketing',group:'Marketing',icon:'CursorClick',tag:'From attention to opportunity',headline:['Be easier to find.','And easier to choose.'],short:'Connect your online presence, content and lead generation.',intro:'Help the right customers discover your business and understand their next step. Bring your online presence, social channels and lead generation activity together around a consistent message.',needs:['Your online presence does not reflect your business.','You want a clearer path from interest to an inquiry.','Your digital activity needs more structure and consistency.'],deliverables:[['Digital presence review','Identify friction in how customers discover and contact you.'],['Content & channel direction','Align your online communication with your audience and brand.'],['Lead generation approach','Define the path from awareness to a relevant business inquiry.']],questions:[['Will you guarantee a number of leads?','No. Results depend on your market, offer, budget and other factors. We agree on objectives and a way to evaluate progress.'],['Is advertising spend included?','Scope, fees and any third-party costs are confirmed in the written proposal before work starts.']],related:['marketing-strategy','growth-optimization']},
 {slug:'brand-development',name:'Brand Development',group:'Marketing',icon:'Diamond',tag:'A business people recognize',headline:['Make your value clear.','Make your brand yours.'],short:'Build a recognizable identity with a consistent message.',intro:'A strong brand helps people understand who you are, what you stand for and why your business is relevant to them. Connect your positioning, identity and communication into one coherent presence.',needs:['Your business has grown beyond its current identity.','Customers do not immediately understand your value.','Your visual style and messaging feel disconnected.'],deliverables:[['Brand foundations','Clarify your positioning, audience and essential message.'],['Identity direction','A coherent creative direction for a recognizable business presence.'],['Consistency framework','Guidance for applying your brand across agreed touchpoints.']],questions:[['Do we have to replace our logo?','Not necessarily. We start with what is already useful and recognizable, then agree what should evolve.'],['Can you help with an existing brand?','Yes. An engagement can focus on refining positioning and consistency rather than starting from zero.']],related:['marketing-strategy','digital-marketing']},
 {slug:'growth-optimization',name:'Growth Optimization',group:'Growth',icon:'ChartLineUp',tag:'Find your next opportunity',headline:['Understand the friction.','Unlock the next step.'],short:'Find opportunities to improve performance and support sustainable growth.',intro:'Growth is easier to work on when you know where momentum is being lost. Review the customer journey, operating priorities and available evidence to identify the improvements worth pursuing.',needs:['You want to understand what is limiting growth.','Parts of the customer journey are losing momentum.','You need to choose between competing improvement ideas.'],deliverables:[['Opportunity review','Identify gaps and opportunities in the agreed business areas.'],['Improvement priorities','Rank potential changes by relevance, effort and expected value.'],['Review framework','Set a practical cadence for examining progress and refining actions.']],questions:[['Do we need perfect data before starting?','No. We begin with the information available and identify what else would help you make better decisions.'],['How quickly will we see results?','Timing depends on the scope and the business context. Milestones and review points are agreed before work starts.']],related:['business-consulting','ongoing-support']},
 {slug:'ongoing-support',name:'Ongoing Support',group:'Growth',icon:'UsersThree',tag:'A partner for what comes next',headline:['Keep the direction clear.','As your business evolves.'],short:'Keep refining your strategy with a long-term partner.',intro:'Business priorities change. Ongoing consulting and strategy refinement give you a way to review what is happening, work through new questions and decide on the next useful improvement.',needs:['You need a sounding board beyond a single project.','Your priorities change as the business grows.','You want more continuity between planning and review.'],deliverables:[['Regular strategic reviews','A shared rhythm for discussing progress and current challenges.'],['Evolving action plan','Keep priorities relevant as your business and market change.'],['Connected guidance','Bring business and marketing decisions into the same conversation.']],questions:[['Is support a fixed subscription?','The frequency, scope, fees and terms are agreed for your engagement. There is no automatic purchase or subscription on this website.'],['Can we start with a focused project?','Yes. A focused engagement can help identify whether ongoing support would be useful.']],related:['growth-optimization','business-consulting']},
];
export const process = [
 {name:'Discover',label:'Understand before advising.',text:'We start with your business, your customers and the change you want to make. Together, we identify the questions that need answering.',input:'Your goals, current challenges and relevant business context.',output:'A shared understanding of the problem and the right scope.',items:['Business context','Customer perspective','Scope & priorities']},
 {name:'Design',label:'Give ambition a clear direction.',text:'We connect the findings into a practical direction: what to focus on, why it matters and how the work should fit together.',input:'The priorities and evidence gathered in discovery.',output:'An agreed roadmap with activities and review points.',items:['Strategic direction','Action roadmap','Measures of progress']},
 {name:'Put into action',label:'Make the plan useful.',text:'We work through the agreed activities with clear communication and responsibilities. Business strategy and marketing stay connected.',input:'An approved scope, relevant materials and timely collaboration.',output:'The agreed work, reviewed together as it develops.',items:['Agreed activities','Shared responsibilities','Regular communication']},
 {name:'Refine',label:'Keep learning. Keep improving.',text:'We review what the work is telling us, discuss new challenges and identify the next useful improvement for your business.',input:'Available results, feedback and changes in your priorities.',output:'Refined priorities and a considered next step.',items:['Progress review','Practical adjustments','Next priorities']},
];
export const engagements = [
 {id:'focused-project',name:'Focused project',eyebrow:'One clear priority',text:'For a specific challenge with a defined scope and a clear outcome.',features:['A focused discovery conversation','Agreed deliverables and responsibilities','Project milestones and a handoff'],fit:'You know the area you want to work on.',cta:'Discuss a project'},
 {id:'growth-partnership',name:'Growth partnership',eyebrow:'Connected progress',text:'For business and marketing priorities that need to move forward together.',features:['A connected strategic roadmap','A coordinated scope across services','Regular reviews and evolving priorities'],fit:'You want a consistent direction across the business.',cta:'Explore a partnership'},
 {id:'strategic-advisory',name:'Strategic advisory',eyebrow:'An ongoing perspective',text:'For leaders who want a thoughtful partner as decisions and priorities evolve.',features:['Recurring consulting conversations','Support with strategic decisions','Continued strategy refinement'],fit:'You need a sounding board for what comes next.',cta:'Discuss advisory support'},
];
export const faqs = [
 ['What does SIRAL help businesses with?','Business consulting, marketing strategy, digital marketing, brand development, growth optimization and ongoing support. We help connect those disciplines around your goals.'],
 ['Do you work with businesses outside Pennsylvania?','Yes. SIRAL works with businesses across the United States. The company is based in Huntingdon Valley, Pennsylvania.'],
 ['How much does an engagement cost?','Pricing depends on the agreed scope. We discuss your needs first and confirm the deliverables, fees and terms in writing before work starts.'],
 ['What happens after I get in touch?','We review your inquiry and discuss your business goals and the right next step. SIRAL typically responds within 24 hours.'],
 ['Can we start with just one service?','Yes. Start with a focused priority, then discuss other services if they would support your goals.'],
];
export const routeList=['/','/services/',...services.map(s=>'/services/'+s.slug+'/'),'/about/','/approach/','/plans/','/contact-us/','/privacy-policy/','/terms-conditions/','/disclaimer/'];
